export const EMPLOYEES:any[] = [
  {id: 1, name: "Christopher Harlow", position: "Associate Solutions Specialist", bio: "Hi, my name is Christopher Harlow, but i prefer to go by Chris. I am married to a beautiful woman named Vanessa and we have a beautiful 6 month old daughter named Lily. I'm coming from Tucson to join the team.  I graduated from the University of Arizona with a major in informatics and a minor in Organizational Leadership. Currently my strongest programming language is Java, but I have some experience in Python, CSS, HTML, JavaScript, and C. I look forward to meeting all of you and working together.", email: "christopher.harlow@siriuscom.com"},
  {id:2, name: "Jenifer Sebastian", position: "Associate Solutions Specialist", bio: "Hey everyone! My name is Jenifer Sebastian, I go by Jen! I'm from Houston. I graduated from the University of Houston in 2015. I have experience with JavaScript as well as Java. Im also familiar with the Ionic Framework. Im moving to Austin solo. I'm really excited about the move & to meet everyone! Hope you guys have a wonderful rest of the week!", email: "jenifer.sebastian@siriuscom.com"},
  {id:3, name: "Braden Filler", position: "Associate Solutions Specialist", bio: "Hi everyone, I'm Braden.  I am currently living in Salt Lake City but I am from Lake Wales, FL, none of you have probably heard of it, I just graduated with a degree in Computer Science.", email: "braden.filler@siriuscom.com"},
  {id:4, name: "Will Cortes", position: "Associate Solutions Specialist", bio: "Hi everyone, sorry for the late day introduction. I just got back from seeing some family today. My name is William Cortes, I usually go by Will. I'm from the Los Angeles area and I went to school nearby in the city of Orange at Chapman University. I just graduated with a major in computer science and a minor in mathematics four weeks ago. I'm looking forward to meeting everyone soon as well.", email: "william.cortes@siriuscom.com"},
  {id:5, name: "Cherie Parsons", position: "Associate Solutions Specialist", bio: "Hi. I'm Cherie. I am from Glendale Arizona and just graduated from NAU this May. I am moving to Austin as of today and am currently packing as I write this. Look forward to meeting all of you.", email: "cherie.parsons@siriuscom.com"},
  {id:6, name: "Scout Martinelli", position: "Associate Solutions Specialist", bio: "", email: "scout.martinelli@siriuscom.com"}

];
