export const EMPLOYEES:any[] = [
  {id: 1, name: "Christopher Harlow", position: "Associate Solutions Specialist", bio: "Hi, my name is Christopher Harlow, but i prefer to go by Chris. I am married to a beautiful woman named Vanessa and we have a beautiful 6 month old daughter named Lily. I'm coming from Tucson to join the team.  I graduated from the University of Arizona with a major in informatics and a minor in Organizational Leadership. Currently my strongest programming language is Java, but I have some experience in Python, CSS, HTML, JavaScript, and C.", email: "christopher.harlow@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5XKUC5A8-ef33df52abba-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5XKUC5A8-ef33df52abba-1024', coverPhoto: 'https://cdn.lennar.net/images/com/images/new-homes/2/74/mhi/market/TUC1v2.jpg?d=20141121T130253' },
  {id:2, name: "Jenifer Sebastian", position: "Associate Solutions Specialist", bio: "Hey everyone! My name is Jenifer Sebastian, I go by Jen! I'm from Houston. I graduated from the University of Houston in 2015. I have experience with JavaScript as well as Angular. Im also familiar with the Ionic Framework. Im moving to Austin solo!", email: "jen.sebastian@siriuscom.com" , imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5XE898EN-d1565b4dc70a-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5XE898EN-d1565b4dc70a-1024', coverPhoto:'http://cdn.wallpapersafari.com/23/92/f2kIXL.jpg'},
  {id:3, name: "Braden Filler", position: "Associate Solutions Specialist", bio: "Hi everyone, I'm Braden.  I am currently living in Salt Lake City but I am from Lake Wales, FL, none of you have probably heard of it, I just graduated with a degree in Computer Science.", email: "braden.filler@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T2XE8732R-U5XKUC5A8-ef33df52abba-1024', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U60DZ8K6E-g5cbe28b682b-1024', coverPhoto:'http://cory-bagley.com/wp-content/uploads/salt-lake-city-utah_august-2011.jpg'},
  {id:4, name: "Will Cortes", position: "Associate Solutions Specialist", bio: "Hi, my name is William Cortes, I usually go by Will. I'm from the Los Angeles and I went to school nearby in the city of Orange at Chapman University. I graduated with a major in computer science and a minor in mathematics.", email: "william.cortes@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5XHRK6DT-829aec1bb8ed-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5XHRK6DT-829aec1bb8ed-1024', coverPhoto: 'http://data.whicdn.com/images/122356594/original.jpg'},
  {id:5, name: "Cherie Parsons", position: "Associate Solutions Specialist", bio: "Hi. I'm Cherie. I am from Glendale Arizona and just graduated from NAU this May. ", email: "cherie.parsons@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5XCSCMC0-0040c9d67f9b-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5XCSCMC0-0040c9d67f9b-1024', coverPhoto: 'http://unleashbb.com/wp-content/uploads/2015/07/Phoenix-Arizona-Skyline-at-Night1-1332x533.png'},
  {id:6, name: "Scout Martinelli", position: "Associate Solutions Specialist", bio: "Hey All, My name is Scout Martinelli I was born and raised in Saint Louis, MO. I recently graduated from Mizzou or the University of Missouri - Columbia with a dual major in electrical engineering and computer engineering with a minor in math and computer science.", email: "scout.martinelli@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5YTDM5RV-4068963ddf67-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5YTDM5RV-4068963ddf67-1024', coverPhoto: 'https://images.fineartamerica.com/images-medium-large-5/st-louis-skyline-at-dusk-gateway-arch-color-panorama-missouri-jon-holiday.jpg'},
];

export const DIRECTORS:any[]=[
  {id:1, name: "Andrew Bell", position: "ACE Program Manager", bio: "I'm Australian and have been in Austin/US for four years. Technically I work for FiveOut, which is the creative agency arm of Sirius.  I manage the Austin Delivery Center where you will all be based. I work in the Mobile team of FiveOut but lately I have been working a lot with VR/AR.", email: "Andrew.Bell@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T5XE8732R-U5XE8738V-4c338380ebf4-72', largeImg: 'https://ca.slack-edge.com/T5XE8732R-U5XE8738V-4c338380ebf4-1024', coverPhoto: 'http://2.bp.blogspot.com/-Naq2xPiM9w0/T_Q8Gy24AxI/AAAAAAAACCg/wa0aQkYYn2U/s1600/opera1-blog.jpg'},
  {id:2, name: "Ravi Vungarala", position:"ACE Program Sponser", bio:" I am the Program Sponser for the ACE Team. I attended Sathyabama University in Chennai, India. Presently, I work as the Technical Director, Heading Mobile, Digital Experience and Social practice. I am also responsible for the growth and development of our Chennai office. ", email: "Ravi.Vungarala@siriuscom.com", imgUrl:'https://ca.slack-edge.com/T2XE8732R-U5XKUC5A8-ef33df52abba-1024', largeImg: 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/3/005/0a5/195/2bd1cfe.jpg', coverPhoto: 'https://2.bp.blogspot.com/-C3nPukB_UVE/Tvnn3IodbAI/AAAAAAAAHTQ/zfMyYyUWtVQ/s1600/Chennai-Images4.jpg'}
]
